version: '3.0'

services:

  gobapi:
    build: src
    ports:
      # To use oauth2-proxy:
      #   Set port to 8000
      #   Set the variables in .env
      # Use port 8001 to bypass the OAuth2 Proxy locally
      - "8141:8001"
    container_name: gobapi
    environment:
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: database
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_INFRA_SERVICES: MESSAGE_SERVICE
      SECURE_SALT: insecure
      SECURE_PASSWORD: insecure
      # OAuth2 Proxy listens on port 8000 and serves as a proxy for UWSGI
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "gobapi.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: "1"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_THREADS: ""
      UWSGI_PROCESSES: "4"
      UWSGI_LAZY: ""
      UWSGI_LAZY_APPS: "1"
      UWSGI_BUFFER_SIZE: "8192"

      # uWSGI timeouts set to 8 hours
      UWSGI_HARAKIRI: "28800"
      UWSGI_MAX_WORKER_LIFETIME: "28800"
      UWSGI_HTTP_TIMEOUT: "28800"
      UWSGI_SOCKET_TIMEOUT: "28800"

      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_URL}

networks:
  default:
    external:
      name: gob-network
