version: '3.4'

services:

  gobapi:
    build:
      context: src
      target: development
    ports:
      # No OAuth2 Proxy
      - "8141:8001"
      # With oauth2-proxy
      #   Set cookie_secure in oauth2-proxy.cfg to false
      #   Uncomment UWSGI_ATTACH_DAEMON2
      # - "8141:8000"
    container_name: gobapi
    environment:
      GOB_SHARED_DIR: /app/shared
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: "${DATABASE_HOST_OVERRIDE:-database}"
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_INFRA_SERVICES: MESSAGE_SERVICE
      SECURE_SALT: insecure
      SECURE_PASSWORD: insecure

      # OAuth2 Proxy listens on port 8000 and serves as a proxy for UWSGI
      UWSGI_HTTP: ":8001"
      UWSGI_MODULE: "gobapi.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: "1"
      UWSGI_ENABLE_THREADS: ""
      UWSGI_PROCESSES: "4"
      UWSGI_LAZY_APPS: "1"
      UWSGI_BUFFER_SIZE: "8192"
      UWSGI_DIE_ON_TERM: "1"
      UWSGI_NEED_APP: "1"
      # UWSGI_ATTACH_DAEMON2: "cmd=./oauth2-proxy --config oauth2-proxy.cfg,freq=3,control=true,stopsignal=15"

      # uWSGI timeouts set to 8 hours
      UWSGI_HARAKIRI: "28800"
      UWSGI_MAX_WORKER_LIFETIME: "28800"
      UWSGI_HTTP_TIMEOUT: "28800"
      UWSGI_SOCKET_TIMEOUT: "28800"

      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_URL}
    env_file: .env
    volumes:
      - gob-volume:/app/shared
      - ./src/gobapi:/app/gobapi
      - ./src/tests:/app/tests
      - ${GOB_CORE_DIR-../GOB-Core}:/app/GOB-Core
      - ${GOB_CONFIG_DIR-../GOB-Config}:/app/GOB-Config

volumes:
  gob-volume:
    external: true

networks:
  default:
    name: gob-network
    external: true
