version: '3.0'

services:

  gobapi:
    build: src
    ports:
      - "8141:8000"
    container_name: gobapi
    environment:
      DATABASE_PORT_OVERRIDE: 5432
      DATABASE_HOST_OVERRIDE: database
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_INFRA_SERVICES: MESSAGE_SERVICE
      UWSGI_HTTP: ":8000"
      UWSGI_MODULE: "gobapi.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_HARAKIRI: 125
      UWSGI_PROCESSES: 2
      UWSGI_HTTP_TIMEOUT: 120


networks:
  default:
    external:
      name: gob-network
