FROM amsterdam/python:3.7-buster
MAINTAINER datapunt@amsterdam.nl

# Install ANTLR
RUN apt-get update -y
RUN apt-get install -y antlr4

# Install api service in /app folder
WORKDIR /app

RUN apt-get update && apt-get -y --no-install-recommends install unixodbc-dev libgdal-dev

# Update C env vars so compiler can find gdal
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

# Install SQL Server driver
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17

# Install required Python packages
COPY requirements.txt /app/
RUN pip3 install --trusted-host pypi.python.org --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir -r requirements.txt
RUN rm requirements.txt
RUN rm -rf /app/src/gobcore/tests
RUN rm -rf /app/src/flask-audit-log/tests

# Copy gob api module
COPY gobapi gobapi

# Copy tests
COPY tests tests
COPY .flake8 .flake8
COPY .coveragerc .coveragerc
COPY test.sh test.sh

# Build
COPY build.sh /app
RUN ./build.sh

# Create directory for gob-volume
RUN mkdir -p /root/gob-volume

# Copy jenkins files
COPY .jenkins /.jenkins
